# Copyright 2022 The Blaze Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[workspace]
members = [
    "native-engine/datafusion-ext-commons",
    "native-engine/datafusion-ext-exprs",
    "native-engine/datafusion-ext-file-formats",
    "native-engine/datafusion-ext-functions",
    "native-engine/datafusion-ext-plans",
    "native-engine/blaze",
    "native-engine/blaze-commons",
    "native-engine/blaze-serde",
]

[profile.dev]
opt-level = 1
overflow-checks = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.pre]
inherits = "release"
incremental = true
debug = false
opt-level = 1
lto = false
codegen-units = 16
strip = true

[patch.crates-io]
arrow = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-arith = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-array = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-buffer = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-cast = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-csv = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-data = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-flight = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-integration-test = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-integration-testing = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-ipc = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-json = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-ord = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-row = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-schema = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-select = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
arrow-string = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
object_store = { git = "https://github.com/richox/arrow-rs.git", rev = "1994e827" }
datafusion = { git = "https://github.com/apache/arrow-datafusion.git", tag = "20.0.0" }
parquet = { path = "patched/parquet-34.0.0-kwai" }
