[package]
name = "blaze-rs"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ahash = "0.7.6"
async-trait = "0.1.52"
ballista-core = "0.6.0"
datafusion = "6.0.0"
env_logger = "0.9.0"
futures = "0.3.19"
jni = "0.19.0"
log = "0.4.14"
prost = "0.8.0"
tempfile = "3.3.0"
timed = "0.2.1"
tokio = "1.15.0"
tokio-stream = "0.1.8"

[profile.dev]
overflow-checks = false
