# Copyright 2022 The Blaze Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[workspace]
members = [
    "native-engine/datafusion-ext-commons",
    "native-engine/datafusion-ext-exprs",
    "native-engine/datafusion-ext-file-formats",
    "native-engine/datafusion-ext-functions",
    "native-engine/datafusion-ext-plans",
    "native-engine/blaze",
    "native-engine/blaze-commons",
    "native-engine/blaze-serde",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1


[profile.test]
debug = false
opt-level = 1
lto = false
codegen-units = 16
overflow-checks = false

[patch.crates-io]
arrow-array = { git = "https://github.com/apache/arrow-rs.git", tag = "28.0.0" }
arrow-buffer = { git = "https://github.com/apache/arrow-rs.git", tag = "28.0.0" }
arrow-cast = { git = "https://github.com/apache/arrow-rs.git", tag = "28.0.0" }
arrow-data = { git = "https://github.com/apache/arrow-rs.git", tag = "28.0.0" }
arrow-ipc = { git = "https://github.com/apache/arrow-rs.git", tag = "28.0.0" }
arrow-schema = { git = "https://github.com/apache/arrow-rs.git", tag = "28.0.0" }
arrow-select = { git = "https://github.com/apache/arrow-rs.git", tag = "28.0.0" }
datafusion = { git = "https://github.com/apache/arrow-datafusion.git", tag = "15.0.0" }
parquet = { path = "patched/parquet-28.0.0-kwai" }

