[package]
name = "blaze-serde"
version = "0.1.0"
edition = "2021"

[features]
default = ["datafusion/simd", "prost/no-recursion-limit"]

[dependencies]
arrow = "28.0.0"
datafusion = "15.0.0"
datafusion-ext-commons = { path = "../datafusion-ext-commons" }
datafusion-ext-exprs = { path = "../datafusion-ext-exprs" }
datafusion-ext-file-formats = { path = "../datafusion-ext-file-formats" }
datafusion-ext-functions = { path = "../datafusion-ext-functions" }
datafusion-ext-plans = { path = "../datafusion-ext-plans" }
log = "0.4.14"
prost = "0.11.0"

[build-dependencies]
tonic-build = "0.8.2"
