[package]
name = "datafusion-ext"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snmalloc-rs = {version = "0.2", features= ["cache-friendly"], optional = true}

parquet-format = { version = "4.0.0" }
arrow = { version = "4.3.0"}
datafusion = { git = "https://github.com/apache/arrow-datafusion.git"}
parquet = { version = "4.3.0" }
