version: "3"

services:
  build-release:
    build: ./rust-nightly
    volumes:
      - ~/.cargo/git:/root/.cargo/git:rw
      - ~/.cargo/registry:/root/.cargo/registry:rw
      - ~/.gradle:/root/.gradle:rw
      - ~/.m2:/root/.m2:rw
      - ./../../:/blaze:rw
      - ./../../target-docker:/blaze/target:rw
      - ./../../target-docker/spark-extension-build:/blaze/spark-extension/build:rw
      - ./../../target-docker/spark-extension-shims-spark303-build:/blaze/spark-extension-shims-spark303/build:rw
      - ./../../target-docker/spark-extension-shims-spark241kwaiae-build:/blaze/spark-extension-shims-spark241kwaiae/build:rw
    environment:
      SHIM: "${SHIM}"
      MODE: "${MODE}"
    command: "bash -c 'source ~/.bashrc && cd /blaze && ./release.sh -Pshim=${SHIM} -Pmode=${MODE}'"
