[package]
name = "datafusion-ext-plans"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["arrow/ffi", "datafusion/simd", "tokio/rt-multi-thread"]

[dependencies]
arrow = "26.0.0"
async-trait = "0.1.56"
blaze-commons = { path = "../blaze-commons" }
datafusion = "14.0.0"
datafusion-ext-commons = { path = "../datafusion-ext-commons" }
futures = "0.3"
itertools = "0.10.3"
jni = "0.20.0"
log = "0.4.14"
once_cell = "1.16.0"
paste = "1.0.7"
tempfile = "3"
tokio = "1.19"
voracious_radix_sort = "1.1.1"
