[package]
name = "datafusion-ext-plans"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["arrow/ffi", "datafusion/simd", "tokio/rt-multi-thread"]

[dependencies]
arrow = "37.0.0"
async-trait = "0.1.56"
bitvec = "1.0.1"
base64 = "0.21.2"
bytes = "1.4.0"
blaze-jni-bridge = { path = "../blaze-jni-bridge" }
bytesize = "1.1.0"
datafusion = "22.0.0"
datafusion-ext-commons = { path = "../datafusion-ext-commons" }
datafusion-ext-exprs = { path = "../datafusion-ext-exprs" }
derivative = "2.2.0"
futures = "0.3"
hashbrown = "0.13.1"
itertools = "0.10.3"
jni = "0.20.0"
log = "0.4.14"
lz4_flex = "0.10.0"
object_store = "0.5.6"
once_cell = "1.16.0"
panic-message = "0.3.0"
parking_lot = "0.12.1"
paste = "1.0.7"
tempfile = "3"
tokio = "1.19"
zstd = "0.12.3"
num = "0.4.0"
