[package]
name = "datafusion-ext-plans"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["arrow/ffi", "datafusion/simd", "tokio/rt-multi-thread"]

[dependencies]
arrow = "28.0.0"
async-trait = "0.1.56"
blaze-commons = { path = "../blaze-commons" }
datafusion = "15.0.0"
datafusion-ext-commons = { path = "../datafusion-ext-commons" }
datafusion-ext-exprs = { path = "../datafusion-ext-exprs" }
derivative = "2.2.0"
futures = "0.3"
hashbrown = "0.13.1"
itertools = "0.10.3"
jni = "0.20.0"
log = "0.4.14"
lz4_flex = "0.9.5"
once_cell = "1.16.0"
panic-message = "0.3.0"
paste = "1.0.7"
smallbox = "0.8.1"
tempfile = "3"
tokio = "1.19"
voracious_radix_sort = "1.1.1"
zstd = "0.11.2"
