[package]
name = "datafusion-ext-exprs"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["arrow/ffi", "datafusion/simd"]

[dependencies]
arrow = "34.0.0"
async-trait = "0.1.56"
blaze-commons = { path = "../blaze-commons" }
bigdecimal = "0.3.0"
datafusion = "20.0.0"
datafusion-ext-commons = { path = "../datafusion-ext-commons" }
jni = "0.20.0"
log = "0.4.14"
num = "0.4.0"
once_cell = "1.11.0"
paste = "1.0.7"
